#!/usr/bin/env python3
import sys
import os
import subprocess

name = sys.argv[1]
count = int(sys.argv[2])

path = os.getcwd()
full_path = path + "/" + name

script_dir = os.path.dirname(os.path.realpath(__file__))
template_path = script_dir + "/template.cpp"

creation = subprocess.Popen(["mkdir", full_path])
creation.wait()
if creation.returncode != 0:
    print(f"Could not create folder with name `{name}`")
paths = []
for i in range(count):
    if i <= 25:
        path_to_file = full_path + "/" + chr(ord("A") + i) + ".cpp"
        name_task = chr(ord("A") + i)
    else:
        path_to_file = full_path + "/" + str(i) + ".cpp"
        name_task = str(i)
    if not os.path.exists(path_to_file):
        creation_file = subprocess.Popen(["cp", template_path, path_to_file])
        creation_file.wait()
        if creation_file.returncode != 0:
            print(f"Could not create folder with name `{name}`")
    else:
        print(f"File with name `{path_to_file}` already exists.")
    paths.append((path_to_file[len(path) + 1 :], name_task))

cmake_lists_path = path + "/CMakeLists.txt"

with open(cmake_lists_path, "a") as f:
    f.write("\n")
    for path, name_task in paths:
        f.write(f"add_executable({name}_{name_task} {path})\n")
